#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
import argparse
import json
from pathlib import Path
import subprocess


def number(value):
    return int(value, 0) if isinstance(value, str) else int(value)


def words(values):
    return ",".join(f"0x{number(value) & 0xffffffff:08x}U" for value in values)


def generate(evidence, output):
    rows = [row for row in evidence["results"] if row["status"] == "ok"]
    lines = [r'''// generated by replay-i386-matrix.py
#include "metalsharp/gem/i386_engine.h"
#include "metalsharp/gem/i386_memory.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>

struct replay_case {
    const char *name; const uint8_t *code; uint32_t code_size;
    uint32_t input[7], memory[8], xmm[4], use_memory, flags_mask;
    uint32_t expected[8], expected_memory[8], expected_xmm[4];
};
''']
    for index, row in enumerate(rows):
        encoding = bytes.fromhex(row["record"]["encoding"])
        lines.append(f"static const uint8_t code_{index}[] = {{{','.join(f'0x{x:02x}U' for x in encoding)}}};")
    lines.append("static const struct replay_case cases[] = {")
    for index, row in enumerate(rows):
        source = row["input"]
        record = row["record"]
        inputs = [source[name] for name in ("eax", "ebx", "ecx", "edx", "esi", "edi", "eflags")]
        expected = [record[name] for name in
                    ("eax", "ebx", "ecx", "edx", "esiDelta", "ediDelta", "eflags", "case")]
        expected_memory = [record[f"memory{x}"] for x in range(8)]
        expected_xmm = [record[f"xmm0_{x}"] for x in range(4)]
        lines.append(f'{{"{row["name"]}",code_{index},sizeof(code_{index}),'
                     f'{{{words(inputs)}}},{{{words(source["memory"])}}},{{{words(source["xmm0"])}}},'
                     f'{1 if source["useMemoryEsi"] else 0}U,{number(row["definedFlagsMask"])}U,'
                     f'{{{words(expected)}}},{{{words(expected_memory)}}},{{{words(expected_xmm)}}}}},')
    lines.append("};")
    lines.append(r'''
static int replay(const struct replay_case *test, enum gem_i386_engine_mode mode,
                  const char *mode_name) {
    const uint32_t code_address = 0x00400000U, data_address = 0x00500000U;
    const uint32_t stack_address = 0x00100000U;
    uint32_t code = code_address, data = data_address, stack = stack_address;
    uint32_t observed_memory[8] = {0};
    struct gem_i386_runtime_config config;
    struct gem_i386_runtime *runtime;
    struct gem_i386_context context;
    struct gem_memory *memory = gem_memory_create();
    enum gem_stop_reason reason;
    unsigned int index;
    int pass = memory != NULL;
    if (pass) pass = gem_i386_memory_reserve(memory, &code, GEM_GUEST_PAGE_SIZE) == GEM_MEMORY_OK;
    if (pass) pass = gem_i386_memory_commit(memory, code, GEM_GUEST_PAGE_SIZE,
                                             GEM_PAGE_EXECUTE_READWRITE) == GEM_MEMORY_OK;
    if (pass) pass = gem_i386_memory_write(memory, code, test->code, test->code_size) == GEM_MEMORY_OK;
    if (pass) pass = gem_i386_memory_reserve(memory, &data, GEM_GUEST_PAGE_SIZE) == GEM_MEMORY_OK;
    if (pass) pass = gem_i386_memory_commit(memory, data, GEM_GUEST_PAGE_SIZE,
                                             GEM_PAGE_READWRITE) == GEM_MEMORY_OK;
    if (pass) pass = gem_i386_memory_write(memory, data, test->memory, sizeof(test->memory)) == GEM_MEMORY_OK;
    if (pass) pass = gem_i386_memory_reserve(memory, &stack, GEM_GUEST_PAGE_SIZE) == GEM_MEMORY_OK;
    if (pass) pass = gem_i386_memory_commit(memory, stack, GEM_GUEST_PAGE_SIZE,
                                             GEM_PAGE_READWRITE) == GEM_MEMORY_OK;
    memset(&config, 0, sizeof(config));
    config.engine_mode = mode;
    config.host_return_sentinel = code_address + test->code_size;
    config.max_budget = 64U;
    runtime = pass ? gem_i386_runtime_create(memory, &config) : NULL;
    pass = pass && runtime != NULL;
    gem_i386_context_initialize(&context, 0x7ffde000U);
    context.eip = code_address;
    context.eflags = test->input[6] | GEM_I386_EFLAGS_REQUIRED;
    context.gpr[GEM_I386_EAX] = test->input[0];
    context.gpr[GEM_I386_EBX] = test->input[1];
    context.gpr[GEM_I386_ECX] = test->input[2];
    context.gpr[GEM_I386_EDX] = test->input[3];
    context.gpr[GEM_I386_ESI] = test->use_memory ? data_address : test->input[4];
    context.gpr[GEM_I386_EDI] = test->input[5];
    context.gpr[GEM_I386_ESP] = stack_address + GEM_GUEST_PAGE_SIZE - 16U;
    context.xmm[0].lo = (uint64_t)test->xmm[0] | ((uint64_t)test->xmm[1] << 32U);
    context.xmm[0].hi = (uint64_t)test->xmm[2] | ((uint64_t)test->xmm[3] << 32U);
    reason = pass ? gem_i386_runtime_run(runtime, &context, 64U) : GEM_STOP_INVARIANT_VIOLATION;
    pass = pass && reason == GEM_STOP_HOST_RETURN;
    if (pass) pass = gem_i386_memory_read(memory, data, observed_memory,
                                           sizeof(observed_memory)) == GEM_MEMORY_OK;
    if (pass) pass = context.gpr[GEM_I386_EAX] == test->expected[0] &&
                     context.gpr[GEM_I386_EBX] == test->expected[1] &&
                     context.gpr[GEM_I386_ECX] == test->expected[2] &&
                     context.gpr[GEM_I386_EDX] == test->expected[3];
    if (pass) pass = context.gpr[GEM_I386_ESI] - (test->use_memory ? data_address : test->input[4]) == test->expected[4] &&
                     context.gpr[GEM_I386_EDI] - test->input[5] == test->expected[5];
    if (pass) pass = (context.eflags & test->flags_mask) == (test->expected[6] & test->flags_mask);
    for (index = 0; pass && index < 8U; ++index) pass = observed_memory[index] == test->expected_memory[index];
    if (pass) pass = (uint32_t)context.xmm[0].lo == test->expected_xmm[0] &&
                     (uint32_t)(context.xmm[0].lo >> 32U) == test->expected_xmm[1] &&
                     (uint32_t)context.xmm[0].hi == test->expected_xmm[2] &&
                     (uint32_t)(context.xmm[0].hi >> 32U) == test->expected_xmm[3];
    printf("{\"name\":\"%s\",\"mode\":\"%s\",\"pass\":%s,\"stopReason\":%u,"
           "\"eax\":\"0x%08x\",\"ebx\":\"0x%08x\",\"ecx\":\"0x%08x\","
           "\"edx\":\"0x%08x\",\"eflags\":\"0x%08x\",\"memory0\":\"0x%08x\","
           "\"xmm0_0\":\"0x%08x\"}\n",
           test->name, mode_name, pass ? "true" : "false", (unsigned int)reason,
           context.gpr[GEM_I386_EAX], context.gpr[GEM_I386_EBX],
           context.gpr[GEM_I386_ECX], context.gpr[GEM_I386_EDX], context.eflags,
           observed_memory[0], (uint32_t)context.xmm[0].lo);
    if (runtime) gem_i386_runtime_destroy(runtime);
    if (memory) gem_memory_destroy(memory);
    return pass ? 0 : 1;
}

int main(void) {
    unsigned int index;
    int failures = 0;
    for (index = 0; index < sizeof(cases) / sizeof(cases[0]); ++index) {
        failures += replay(&cases[index], GEM_I386_ENGINE_INTERPRETER, "interpreter");
        failures += replay(&cases[index], GEM_I386_ENGINE_JIT, "jit");
    }
    return failures ? 1 : 0;
}
''')
    output.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--evidence", required=True, type=Path)
    parser.add_argument("--source-root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--build-dir", required=True, type=Path)
    parser.add_argument("--work", required=True, type=Path)
    args = parser.parse_args()
    evidence = json.loads(args.evidence.read_text(encoding="utf-8"))
    work = args.work.resolve(); work.mkdir(parents=True, exist_ok=True)
    source = work / "i386-rosetta-replay.c"
    executable = work / "i386-rosetta-replay"
    generate(evidence, source)
    subprocess.run(["/usr/bin/cc", "-std=c11", "-Wall", "-Wextra", "-Werror", "-arch", "arm64",
                    "-I", str(args.source_root.resolve() / "include"), str(source),
                    str(args.build_dir.resolve() / "libmetalsharp_gem.a"),
                    str(args.build_dir.resolve() / "libblink_gem_archive.a"), "-lz", "-lm",
                    "-o", str(executable)], check=True)
    run = subprocess.run([str(executable)], capture_output=True, text=True)
    rows = [json.loads(line) for line in run.stdout.splitlines() if line.startswith("{")]
    result = {"schemaVersion": 1, "sourceEvidence": str(args.evidence.resolve()),
              "total": len(rows), "passed": sum(1 for row in rows if row["pass"]),
              "failed": [row for row in rows if not row["pass"]], "rows": rows,
              "exitCode": run.returncode, "stderr": run.stderr}
    output = work / "i386-rosetta-replay.json"
    output.write_text(json.dumps(result, sort_keys=True, indent=2) + "\n", encoding="utf-8")
    print(output)


if __name__ == "__main__": main()
