#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate a pinned Dynarmic A64 visitor that reports every Reg/Vec operand.

The decoder's matcher calls visitor methods whose signatures are the operand
schema.  Generating this visitor from the fetched, pinned translator interface
keeps operand roles synchronized with the exact decoder used by the engine.
"""
import pathlib
import re
import sys

if len(sys.argv) != 3:
    raise SystemExit("usage: generate_arm64ec_forbidden_decoder.py IMPL_H OUTPUT_H")

impl = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
output = pathlib.Path(sys.argv[2])
# All translator decoder handlers are deliberately one declaration per line.
declarations = re.findall(r"^    bool ([A-Za-z_][A-Za-z0-9_]*)\((.*)\);$", impl, re.MULTILINE)
if not declarations:
    raise SystemExit("no Dynarmic translator handlers found")

lines = [
    "// Generated by tools/generate_arm64ec_forbidden_decoder.py; do not edit.",
    "// SPDX-License-Identifier: Apache-2.0",
    "#pragma once",
    "",
    "#include <cstdint>",
    "#include \"dynarmic/frontend/A64/a64_types.h\"",
    "#include \"dynarmic/frontend/imm.h\"",
    "",
    "namespace mswr {",
    "using Dynarmic::Imm;",
    "using namespace Dynarmic::A64;",
    "struct ForbiddenRegisterVisitor final {",
    "    using instruction_return_type = bool;",
    "    bool forbidden = false;",
    "    bool Check(Dynarmic::A64::Reg value) {",
    "        const auto index = static_cast<std::uint32_t>(value);",
    "        forbidden = forbidden || index == 13U || index == 14U || index == 23U ||",
    "                    index == 24U || index == 28U;",
    "        return forbidden;",
    "    }",
    "    bool Check(Dynarmic::A64::Vec value) {",
    "        forbidden = forbidden || static_cast<std::uint32_t>(value) >= 16U;",
    "        return forbidden;",
    "    }",
]
for name, args in declarations:
    checks = []
    variables = []
    if args.strip():
        for arg in args.split(", "):
            # The final token is the parameter name. Only architectural GPR/SIMD
            # types are recorded; immediates and system fields are intentionally not.
            tokens = arg.rsplit(" ", 1)
            if len(tokens) != 2:
                raise SystemExit(f"cannot parse parameter {arg!r} for {name}")
            typ, var = tokens
            variables.append(var)
            if typ in ("Reg", "Vec"):
                checks.append(f"Check({var})")
    ignored = " ".join(f"(void){var};" for var in variables)
    body = " || ".join(checks) if checks else "false"
    lines.append(f"    bool {name}({args}) {{ {ignored} return {body}; }}")
lines += ["};", "} // namespace mswr", ""]
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text("\n".join(lines), encoding="utf-8")
